name: Boostrap for Azure infra 

on:
    push: 
        branches:
           -  main

permissions:
  id-token: write
  contents: read

env: 
   TF_WORKDIR: ${{ vars.TF_WORKDIR }}
   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   AZURE_SUB_ID: ${{secrets.AZURE_SUB_ID}}
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install git-crypt
      run: sudo apt-get update && sudo apt-get install -y git-crypt
    - name: Unlock git-crypt
      run: |
        echo "${{ secrets.GIT_CRYPT_KEY_B64 }}" | base64 -d > /tmp/git-crypt.key
        git-crypt unlock /tmp/git-crypt.key
    - uses: azure/login@v2
      with:
       client-id: ${{ secrets.AZURE_CLIENT_ID }}
       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - uses: hashicorp/setup-terraform@v3
    - run: terraform init -input=false 
      working-directory: ${{ vars.TF_WORKDIR }}
    - run: terraform apply -input=false -auto-approve
      working-directory: ${{ vars.TF_WORKDIR }}
