name: Boostrap for Azure infra

on:
    push: 
        branches:
           -  main
    workflow_dispatch:
      inputs:
        apply: 
          description: "Apply infra"
          required: false
          type: boolean
        destroy: 
          description: "Destroy infra"
          required: false
          type: boolean

permissions:
  id-token: write
  contents: read

env: 
   TF_WORKDIR: ${{ vars.TF_WORKDIR }}
   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   AZURE_SUB_ID: ${{secrets.AZURE_SUB_ID}}
   TF_STATE_RG: ${{ vars.TF_STATE_RG }}
   TF_STATE_SA: ${{ vars.TF_STATE_SA }}
   TF_STATE_CONTAINER: ${{ vars.TF_STATE_CONTAINER }}
   TF_STATE_KEY: ${{ vars.TF_STATE_KEY }}
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install git-crypt
      run: sudo apt-get update && sudo apt-get install -y git-crypt
    - name: Unlock git-crypt
      run: |
        echo "${{ secrets.GIT_CRYPT_KEY_B64 }}" | base64 -d > /tmp/git-crypt.key
        git-crypt unlock /tmp/git-crypt.key
    - uses: azure/login@v2
      with:
       client-id: ${{ secrets.AZURE_CLIENT_ID }}
       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - uses: hashicorp/setup-terraform@v3
    - run: |
        terraform init -input=false \
          -backend-config="resource_group_name=${{ env.TF_STATE_RG }}" \
          -backend-config="storage_account_name=${{ env.TF_STATE_SA }}" \
          -backend-config="container_name=${{ env.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ env.TF_STATE_KEY }}"
      working-directory: ${{ vars.TF_WORKDIR }}
    - run: terraform plan -input=false
      working-directory: ${{ vars.TF_WORKDIR }}

  apply:
    if: ${{ github.event.inputs.apply == 'true' }}
    needs: bootstrap
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install git-crypt
      run: sudo apt-get update && sudo apt-get install -y git-crypt
    - name: Unlock git-crypt
      run: |
        echo "${{ secrets.GIT_CRYPT_KEY_B64 }}" | base64 -d > /tmp/git-crypt.key
        git-crypt unlock /tmp/git-crypt.key
    - uses: azure/login@v2
      with:
       client-id: ${{ secrets.AZURE_CLIENT_ID }}
       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - uses: hashicorp/setup-terraform@v3
    - run: |
        terraform init -input=false \
          -backend-config="resource_group_name=${{ env.TF_STATE_RG }}" \
          -backend-config="storage_account_name=${{ env.TF_STATE_SA }}" \
          -backend-config="container_name=${{ env.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ env.TF_STATE_KEY }}"
      working-directory: ${{ vars.TF_WORKDIR }}
    - run: terraform apply -input=false -auto-approve
      working-directory: ${{ vars.TF_WORKDIR }}

  destroy:
    if: ${{ github.event.inputs.destroy == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
       client-id: ${{ secrets.AZURE_CLIENT_ID }}
       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - uses: hashicorp/setup-terraform@v3
    - run: |
        terraform init -input=false \
          -backend-config="resource_group_name=${{ env.TF_STATE_RG }}" \
          -backend-config="storage_account_name=${{ env.TF_STATE_SA }}" \
          -backend-config="container_name=${{ env.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ env.TF_STATE_KEY }}"
      working-directory: ${{ vars.TF_WORKDIR }}
    - run: terraform destroy -input=false 
      working-directory: ${{ vars.TF_WORKDIR }}
